include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore

# analyzer:
#   errors:
#     public_member_api_docs: ignore
#     lines_longer_than_80_chars: ignore

# linter:
#   rules:
#     line_length: 100