name: skeleton_pdf
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  device_preview: ^1.3.1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  hydrated_bloc: ^10.1.1
  meta: ^1.16.0
  path_provider: ^2.1.5
  sizer: ^3.0.5
  slang: ^4.7.0
  slang_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^4.7.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400 # Regular
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700 # Bold
        - asset: assets/fonts/WorkSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100 # Thin
        - asset: assets/fonts/WorkSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200 # Extra Light
        - asset: assets/fonts/WorkSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300 # Light
        - asset: assets/fonts/WorkSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500 # Medium
        - asset: assets/fonts/WorkSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600 # Semi Bold
        - asset: assets/fonts/WorkSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800 # Extra Bold
        - asset: assets/fonts/WorkSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900 # Black
        - asset: assets/fonts/WorkSans-BlackItalic.ttf
          style: italic
          weight: 900
